services:
  mail-bot:
    build: .
    container_name: mail-bot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - TZ=Europe/Moscow

    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    networks:
      custom_network:
        ipv4_address: 10.187.0.10

    healthcheck:
      test: ["CMD", "pgrep", "-f", "main.py"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.187.0.0/24
