version: '3.8'

services:
  app:
    build: .
    container_name: mail-bot
    environment:
      - IMAP_SERVER=${IMAP_SERVER}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - .:/app